In [6]:
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
import nltk

In [7]:
#read data
df=pd.read_csv("data_spam.csv",encoding='latin-1')
df.head(5)

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [8]:
df.shape

(5572, 5)

In [9]:
#drop cols
df.drop('Unnamed: 2',axis=1, inplace=True)
df.drop('Unnamed: 3',axis=1, inplace=True)
df.drop('Unnamed: 4',axis=1, inplace=True)
print(df.shape)
df.head(5)

(5572, 2)


v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [10]:
df.isnull().sum()

v1    0
v2    0
dtype: int64

In [11]:
df.duplicated().sum()

403

In [12]:
df = df.drop_duplicates()
df.shape

(5169, 2)

In [13]:
#convert text to lower case
df['v2'] = df['v2'].str.lower()
df.head(5)

v1                                                 v2
0   ham  go until jurong point, crazy.. available only ...
1   ham                      ok lar... joking wif u oni...
2  spam  free entry in 2 a wkly comp to win fa cup fina...
3   ham  u dun say so early hor... u c already then say...
4   ham  nah i don't think he goes to usf, he lives aro...

In [14]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Ahmed
[nltk_data]     Ali\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [15]:

from nltk.corpus import stopwords
stopwords = set(stopwords.words('english'))
stopwords

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [16]:
#remove stopwords
def remove_stopwords(x):
    return " ".join([word for word in str(x).split() if word not in stopwords])
df['v2']= df['v2'].apply(lambda x: remove_stopwords(x))

In [17]:
df.head(5)

v1                                                 v2
0   ham  go jurong point, crazy.. available bugis n gre...
1   ham                      ok lar... joking wif u oni...
2  spam  free entry 2 wkly comp win fa cup final tkts 2...
3   ham          u dun say early hor... u c already say...
4   ham            nah think goes usf, lives around though

In [18]:
#apply tokenization
import re # regular text
def tokenize(text):
  # ignore non alpha
  tokens = re.split('\W', text)
  return tokens
df["v2"] = df["v2"].apply( lambda x:tokenize(x))
df.head(5)

v1                                                 v2
0   ham  [go, jurong, point, , crazy, , , available, bu...
1   ham         [ok, lar, , , , joking, wif, u, oni, , , ]
2  spam  [free, entry, 2, wkly, comp, win, fa, cup, fin...
3   ham  [u, dun, say, early, hor, , , , u, c, already,...
4   ham   [nah, think, goes, usf, , lives, around, though]

In [19]:
#apply stemming
ps = nltk.PorterStemmer()
def stemming(text):
  Stext=[ps.stem(i) for i in text]
  return Stext
df["v2"]=df["v2"].apply(lambda x: stemming(x))
df.head(5)

v1                                                 v2
0   ham  [go, jurong, point, , crazi, , , avail, bugi, ...
1   ham           [ok, lar, , , , joke, wif, u, oni, , , ]
2  spam  [free, entri, 2, wkli, comp, win, fa, cup, fin...
3   ham  [u, dun, say, earli, hor, , , , u, c, alreadi,...
4   ham     [nah, think, goe, usf, , live, around, though]

In [20]:

import nltk
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to C:\Users\Ahmed
[nltk_data]     Ali\AppData\Roaming\nltk_data...


True

In [21]:
#apply lemmatization
nltk.download('wordnet')
wn = nltk.WordNetLemmatizer()
def lemmatiztion(tokentext):
  text=[wn.lemmatize(word) for word in tokentext]
  return text

df["v2"] =df["v2"].apply(lambda x : lemmatiztion(x))
df.head(5)

[nltk_data] Downloading package wordnet to C:\Users\Ahmed
[nltk_data]     Ali\AppData\Roaming\nltk_data...


v1                                                 v2
0   ham  [go, jurong, point, , crazi, , , avail, bugi, ...
1   ham           [ok, lar, , , , joke, wif, u, oni, , , ]
2  spam  [free, entri, 2, wkli, comp, win, fa, cup, fin...
3   ham  [u, dun, say, earli, hor, , , , u, c, alreadi,...
4   ham     [nah, think, goe, usf, , live, around, though]

In [22]:
#feature generation length of message 
df["msg_length"]=df["v2"].apply(lambda x: len(x))
df.head(5)

v1                                                 v2  msg_length
0   ham  [go, jurong, point, , crazi, , , avail, bugi, ...          25
1   ham           [ok, lar, , , , joke, wif, u, oni, , , ]          12
2  spam  [free, entri, 2, wkli, comp, win, fa, cup, fin...          29
3   ham  [u, dun, say, earli, hor, , , , u, c, alreadi,...          15
4   ham     [nah, think, goe, usf, , live, around, though]           8

In [23]:
#feature generation using precentage of puncutaions 
import string
def punctuation_count(text):
  count=sum([1 for c in text if c in string.punctuation])
  return 100*count/len(text)

df["punc_percentage"]=df["v2"].apply(lambda x: punctuation_count(x))
df.head(5)

v1                                                 v2  msg_length  \
0   ham  [go, jurong, point, , crazi, , , avail, bugi, ...          25   
1   ham           [ok, lar, , , , joke, wif, u, oni, , , ]          12   
2  spam  [free, entri, 2, wkli, comp, win, fa, cup, fin...          29   
3   ham  [u, dun, say, earli, hor, , , , u, c, alreadi,...          15   
4   ham     [nah, think, goe, usf, , live, around, though]           8   

   punc_percentage  
0        36.000000  
1        50.000000  
2         3.448276  
3        40.000000  
4        12.500000

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

# fit the vectorizer on all words
vectorizer.fit(df['v2'].apply(lambda x: ' '.join(x)))

# transform (count of each word in the vocabulary for each document.)
bag_of_words = vectorizer.transform(df['v2'].apply(lambda x: ' '.join(x)))

# create a new DataFrame with the bag of words representation
bow_df=pd.DataFrame(bag_of_words.toarray(), columns=vectorizer.get_feature_names_out())

# concatenate the original DataFrame and the bag of words DataFrame
result_df = pd.concat([df, bow_df], axis=1)

# print the result DataFrame
print(result_df)




        v1                                                 v2  msg_length  \
0      ham  [go, jurong, point, , crazi, , , avail, bugi, ...        25.0   
1      ham           [ok, lar, , , , joke, wif, u, oni, , , ]        12.0   
2     spam  [free, entri, 2, wkli, comp, win, fa, cup, fin...        29.0   
3      ham  [u, dun, say, earli, hor, , , , u, c, alreadi,...        15.0   
4      ham     [nah, think, goe, usf, , live, around, though]         8.0   
...    ...                                                ...         ...   
5105   NaN                                                NaN         NaN   
5108   NaN                                                NaN         NaN   
5129   NaN                                                NaN         NaN   
5141   NaN                                                NaN         NaN   
5164   NaN                                                NaN         NaN   

      punc_percentage   00  000  000pe  008704050406  0089  0121  ...   ó_ 

In [25]:
if any(bag_of_words.toarray()[0]):
    print('Bag of words contains non-zero elements')
else:
    print('Bag of words is all zeros')

Bag of words contains non-zero elements


In [26]:
#split dataset

from sklearn.model_selection import train_test_split
y=df['v1']
xtrain, xtest, ytrain, ytest = train_test_split(bow_df, y, test_size=0.25, random_state=0)

In [27]:
# SVM Algo
from sklearn import svm
svcclassifier = svm.SVC(kernel='linear')
svcclassifier.fit(xtrain, ytrain)
y_pred = svcclassifier.predict(xtest)


In [28]:
# Model Evaluation for SVM
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
print(confusion_matrix(ytest, y_pred))
print( accuracy_score(ytest, y_pred))
print(precision_score(ytest, y_pred,pos_label="spam"))
print(recall_score(ytest, y_pred,pos_label="spam"))
print(f1_score(ytest, y_pred,pos_label="spam"))

[[1119    2]
 [  20  152]]
0.982985305491106
0.987012987012987
0.8837209302325582
0.9325153374233128


In [29]:
#desision tree algo
from sklearn.tree import DecisionTreeClassifier
dtmodel = DecisionTreeClassifier(criterion="entropy", random_state=50)
dtmodel.fit(xtrain.values, ytrain.values)
dt_pred = dtmodel.predict(xtest.values)


In [30]:
# Model Evaluation for desision tree alg
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
print(confusion_matrix(ytest, dt_pred))
print(accuracy_score(ytest, dt_pred))
print(precision_score(ytest, dt_pred,pos_label="ham"))
print(recall_score(ytest, dt_pred,pos_label="ham"))
print(f1_score(ytest, dt_pred,pos_label="ham"))

[[1102   19]
 [  26  146]]
0.9651972157772621
0.9769503546099291
0.9830508474576272
0.9799911071587373


In [31]:
#NaiveBayesClassifier
from sklearn.naive_bayes import MultinomialNB
NaiveBayes=MultinomialNB()
NaiveBayes.fit(xtrain.values, ytrain.values)
NB_pred = NaiveBayes.predict(xtest.values)



In [32]:
# Model Evaluation for Naive Bayes alg
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
print(confusion_matrix(ytest, NB_pred))
print( accuracy_score(ytest, NB_pred))
print(precision_score(ytest, NB_pred,pos_label="ham"))
print(recall_score(ytest, NB_pred,pos_label="ham"))
print(f1_score(ytest, NB_pred,pos_label="ham"))

[[1110   11]
 [  11  161]]
0.982985305491106
0.9901873327386262
0.9901873327386262
0.9901873327386262
